apiVersion: v2
name: mealie
description: A Helm chart for mealie
type: application
version: 1.0.0
appVersion: "3.5.0"
keywords:
  - mealie
  - recipes
  - recipe-manager
  - meal-planning
  - kubernetes

home: https://mealie.io
sources:
  - https://github.com/mealie-recipes/mealie
  - https://github.com/codefuturist/helm-charts

maintainers:
  - name: codefuturist
    email: 58808821+codefuturist@users.noreply.github.com

dependencies:
  - name: common
    repository: file://../../libs/common
    version: 2.x.x
    tags:
      - bitnami-common
