apiVersion: v2
name: mealie
description: A Helm chart for mealie
type: application
version: 0.1.1
appVersion: 1.0.0
keywords:
- mealie
- kubernetes
maintainers:
- name: Your Name
  email: your.email@example.com

dependencies:
  - name: common
    repository: file://../../libs/common
    version: 2.x.x
    tags:
      - bitnami-common
