apiVersion: v2
name: actualbudget
description: A Helm chart for Actual Budget - A local-first personal finance app
type: application
version: 1.0.0
appVersion: "25.11.0"

keywords:
  - actualbudget
  - actual
  - budget
  - finance
  - personal-finance
  - money
  - kubernetes

home: https://actualbudget.org
sources:
  - https://github.com/actualbudget/actual
  - https://github.com/codefuturist/helm-charts

maintainers:
  - name: codefuturist
    email: 58808821+codefuturist@users.noreply.github.com

icon: https://actualbudget.org/img/actual.png

dependencies:
  - name: common
    repository: file://../../libs/common
    version: 2.x.x
    tags:
      - bitnami-common

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: Fixed Chart.yaml metadata (was incorrectly copied from metube)
    - kind: changed
      description: Updated appVersion to pinned version 25.11.0
