{{/*
Copyright codefuturist
SPDX-License-Identifier: MIT
*/}}

{{- if and .Values.persistence.config.enabled (not .Values.persistence.config.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netbootxyz.configPvcName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $) | nindent 4 }}
    app.kubernetes.io/component: config
  {{- if or .Values.persistence.config.annotations .Values.commonAnnotations }}
  {{- $annotations := include "common.tplvalues.merge" (dict "values" (list .Values.persistence.config.annotations .Values.commonAnnotations) "context" .) }}
  annotations: {{- include "common.tplvalues.render" (dict "value" $annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  accessModes:
  {{- range .Values.persistence.config.accessModes }}
    - {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}
  {{- include "common.storage.class" (dict "persistence" .Values.persistence.config "global" .Values.global) | nindent 2 }}
  {{- if .Values.persistence.config.selector }}
  selector: {{- include "common.tplvalues.render" (dict "value" .Values.persistence.config.selector "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
