{{- if and .Values.metube.cookies.enabled (not .Values.metube.cookies.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metube.cookiesSecretName" . }}
  namespace: {{ include "metube.namespace" . }}
  labels:
    {{- include "metube.labels" . | nindent 4 }}
type: Opaque
data:
  cookies.txt: {{ .Values.metube.cookies.cookieFile | b64enc | quote }}
{{- end }}
---
{{- if and .Values.metube.https (not .Values.metube.existingTlsSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metube.tlsSecretName" . }}
  namespace: {{ include "metube.namespace" . }}
  labels:
    {{- include "metube.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.metube.certFile | b64enc | quote }}
  tls.key: {{ .Values.metube.keyFile | b64enc | quote }}
{{- end }}
