# Default values for paperless-ngx
livenessProbe:
  ## @param livenessProbe.enabled Enable livenessProbe
  ##
  enabled: true

  ## @param livenessProbe.initialDelaySeconds Initial delay seconds for livenessProbe
  ##
  initialDelaySeconds: 30

  ## @param livenessProbe.periodSeconds Period seconds for livenessProbe
  ##
  periodSeconds: 10

  ## @param livenessProbe.timeoutSeconds Timeout seconds for livenessProbe
  ##
  timeoutSeconds: 5

  ## @param livenessProbe.failureThreshold Failure threshold for livenessProbe
  ##
  failureThreshold: 6

  ## @param livenessProbe.successThreshold Success threshold for livenessProbe
  ##
  successThreshold: 1

readinessProbe:
  ## @param readinessProbe.enabled Enable readinessProbe
  ##
  enabled: true

  ## @param readinessProbe.initialDelaySeconds Initial delay seconds for readinessProbe
  ##
  initialDelaySeconds: 10

  ## @param readinessProbe.periodSeconds Period seconds for readinessProbe
  ##
  periodSeconds: 10

  ## @param readinessProbe.timeoutSeconds Timeout seconds for readinessProbe
  ##
  timeoutSeconds: 5

  ## @param readinessProbe.failureThreshold Failure threshold for readinessProbe
  ##
  failureThreshold: 6

  ## @param readinessProbe.successThreshold Success threshold for readinessProbe
  ##
  successThreshold: 1

startupProbe:
  ## @param startupProbe.enabled Enable startupProbe
  ##
  enabled: true

  ## @param startupProbe.initialDelaySeconds Initial delay seconds for startupProbe
  ##
  initialDelaySeconds: 0

  ## @param startupProbe.periodSeconds Period seconds for startupProbe
  ##
  periodSeconds: 10

  ## @param startupProbe.timeoutSeconds Timeout seconds for startupProbe
  ##
  timeoutSeconds: 5

  ## @param startupProbe.failureThreshold Failure threshold for startupProbe
  ##
  failureThreshold: 30

  ## @param startupProbe.successThreshold Success threshold for startupProbe
  ##
  successThreshold: 1

## @section Scheduling Configuration

## @param nodeSelector Node labels for pod assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
##
nodeSelector: {}

## @param tolerations Tolerations for pod assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
##
tolerations: []

## @param affinity Affinity for pod assignment
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity
##
affinity: {}

## @param podAnnotations Annotations for Paperless-ngx pods
##
podAnnotations: {}

## @param podLabels Extra labels for Paperless-ngx pods
##
podLabels: {}

## @section Network Policy

## Network Policy configuration
## ref: https://kubernetes.io/docs/concepts/services-networking/network-policies/
##
networkPolicy:
  ## @param networkPolicy.enabled Enable network policies
  ##
  enabled: false

  ## @param networkPolicy.allowExternal Allow external traffic
  ##
  allowExternal: true

  ## @param networkPolicy.extraIngress Additional ingress rules
  ##
  extraIngress: []

  ## @param networkPolicy.extraEgress Additional egress rules
  ##
  extraEgress: []

## @section Monitoring

## Prometheus Operator ServiceMonitor configuration
##
metrics:
  ## @param metrics.enabled Enable Prometheus metrics
  ##
  enabled: false

  serviceMonitor:
    ## @param metrics.serviceMonitor.enabled Create ServiceMonitor resource for scraping metrics using PrometheusOperator
    ##
    enabled: false

    ## @param metrics.serviceMonitor.namespace Namespace in which Prometheus is running
    ##
    namespace: ""

    ## @param metrics.serviceMonitor.interval Interval at which metrics should be scraped
    ##
    interval: 30s

    ## @param metrics.serviceMonitor.scrapeTimeout Timeout after which the scrape is ended
    ##
    scrapeTimeout: 10s

    ## @param metrics.serviceMonitor.labels Additional labels that can be used so ServiceMonitor will be discovered by Prometheus
    ##
    labels: {}

    ## @param metrics.serviceMonitor.selector Prometheus instance selector labels
    ##
    selector: {}

    ## @param metrics.serviceMonitor.relabelings RelabelConfigs to apply to samples before scraping
    ##
    relabelings: []

    ## @param metrics.serviceMonitor.metricRelabelings MetricRelabelConfigs to apply to samples before ingestion
    ##
    metricRelabelings: []

    ## @param metrics.serviceMonitor.honorLabels Specify honorLabels parameter to add the scrape endpoint
    ##
    honorLabels: false

    ## @param metrics.serviceMonitor.jobLabel The name of the label on the target service to use as the job name in prometheus.
    ##
    jobLabel: ""

## @section Extra Configuration

## @param extraEnvVars Array with extra environment variables to add to Paperless-ngx container
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []

## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for Paperless-ngx container
##
extraEnvVarsCM: ""

## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for Paperless-ngx container
##
extraEnvVarsSecret: ""

## @param extraVolumes Optionally specify extra list of additional volumes for the Paperless-ngx pod(s)
##
extraVolumes: []

## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for the Paperless-ngx container(s)
##
extraVolumeMounts: []

## Init containers to add to the Paperless-ngx pod(s)
##
initContainers: []

## Sidecar containers to add to the Paperless-ngx pod(s)
##
sidecars: []
