{{- if or .Values.redisInsight.encryptionKey .Values.redisInsight.tls.key .Values.redisInsight.tls.cert (gt (len .Values.redisInsight.connections) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redisinsight.fullname" . }}
  namespace: {{ include "redisinsight.namespace" . }}
  labels:
    {{- include "redisinsight.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if and .Values.redisInsight.encryptionKey (not .Values.redisInsight.existingEncryptionKeySecret) }}
  encryptionKey: {{ .Values.redisInsight.encryptionKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.redisInsight.tls.enabled }}
  {{- if and .Values.redisInsight.tls.key (not .Values.redisInsight.tls.existingSecret) }}
  tls.key: {{ .Values.redisInsight.tls.key | b64enc | quote }}
  {{- end }}
  {{- if and .Values.redisInsight.tls.cert (not .Values.redisInsight.tls.existingSecret) }}
  tls.crt: {{ .Values.redisInsight.tls.cert | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- if and (gt (len .Values.redisInsight.connections) 0) (not .Values.redisInsight.existingConnectionPasswordsSecret) }}
  {{- range $conn := .Values.redisInsight.connections }}
  {{- if $conn.password }}
  password-{{ $conn.id }}: {{ $conn.password | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
