{{- if (.Values.configMap).enabled }}
{{- range $nameSuffix, $data := .Values.configMap.files }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "homarr.name" $ }}-{{ $nameSuffix }}
  namespace: {{ template "homarr.namespace" $ }}
  labels:
  {{- include "homarr.labels" $ | nindent 4 }}
{{- if $.Values.configMap.additionalLabels }}
{{ toYaml $.Values.configMap.additionalLabels | indent 4 }}
{{- end }}
{{- if $.Values.configMap.annotations }}
  annotations:
{{ toYaml $.Values.configMap.annotations | indent 4 }}
{{- end }}
data:
{{ include "homarr.tplvalues.render" ( dict "value" $data "context" $ ) | indent 2 }}
{{- end }}
{{- end }}
