{{- if and (.Values.endpointMonitor).enabled (.Capabilities.APIVersions.Has "endpointmonitor.stakater.com/v1alpha1") (or (and .Values.route .Values.route.enabled) (and .Values.ingress .Values.ingress.enabled))}}
---
apiVersion: endpointmonitor.stakater.com/v1alpha1
kind: EndpointMonitor
metadata:
  name: {{ template "homarr.name" . }}
  namespace: {{ include "homarr.namespace" . }}
  labels:
  {{- include "homarr.labels" $ | nindent 4 }}
{{- if .Values.endpointMonitor.additionalLabels }}
{{ toYaml .Values.endpointMonitor.additionalLabels | indent 4 }}
{{- end }}
{{- if .Values.endpointMonitor.annotations }}
  annotations:
{{ toYaml .Values.endpointMonitor.annotations | indent 4 }}
{{- end }}
spec:
  forceHttps: true
  urlFrom:
{{- if and .Values.route .Values.route.enabled }}
    routeRef:
      name:  {{ template "homarr.name" . }}
{{- end }}
{{- if and .Values.ingress .Values.ingress.enabled }}
    ingressRef:
      name:  {{ template "homarr.name" . }}
{{- end }}
{{- if .Values.endpointMonitor.additionalConfig }}
{{ toYaml .Values.endpointMonitor.additionalConfig | indent 2 }}
{{- end }}
{{- end }}
