{{- if or .Values.pdb.minAvailable .Values.pdb.maxUnavailable | and .Values.pdb.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  labels:
    {{- include "homarr.labels" $ | nindent 4 }}
  name: {{ template "homarr.name" . }}
  namespace: {{ include "homarr.namespace" . }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "homarr.selectorLabels" . | nindent 6 }}
{{- end }}
