{{- if (.Values.secretProviderClass).enabled }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name }}
  namespace: {{ include "homarr.namespace" . }}
  labels:
  {{- include "homarr.labels" $ | nindent 4 }}
spec:
  provider: {{ .Values.secretProviderClass.provider }}
  parameters:
    {{- if .Values.secretProviderClass.vaultAddress }}
    vaultAddress: {{ .Values.secretProviderClass.vaultAddress }}
    {{- end }}
    roleName: {{ include "homarr.tplvalues.render" (dict "value" .Values.secretProviderClass.roleName "context" $) }}
    {{- if .Values.secretProviderClass.objects }}
    objects:
    {{ toYaml .Values.secretProviderClass.objects | indent 4 }}
    {{- end }}
  {{- if .Values.secretProviderClass.secretObjects }}
  secretObjects:
  {{- range $value := .Values.secretProviderClass.secretObjects }}
    - data: {{- toYaml $value.data | nindent 8 }}
      secretName: {{ $value.secretName }}
      type: {{ $value.type }}
  {{- end }}
  {{- end }}
{{- end }}
