{{- if and .Values.rbac.enabled .Values.rbac.serviceAccount.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ default (include "homarr.name" .) .Values.rbac.serviceAccount.name }}
  namespace: {{ template "homarr.namespace" . }}
  labels:
    {{- include "homarr.labels" $ | nindent 4 }}
    {{- with .Values.rbac.serviceAccount.additionalLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.rbac.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.deployment.openshiftOAuthProxy.enabled }}
    serviceaccounts.openshift.io/oauth-redirectreference.primary:
      {{- $reference := include "application.sa.oauth-redirectreference" . | fromYaml }}
      {{- toRawJson $reference | quote | nindent 6 }}
    {{- end }}
{{- end }}
