{{- if and .Values.vpa.enabled (.Capabilities.APIVersions.Has "autoscaling.k8s.io/v1/VerticalPodAutoscaler") }}
---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "homarr.name" . }}
  namespace: {{ template "homarr.namespace" . }}
  labels:
    {{- include "homarr.labels" . | nindent 4 }}
    {{- with .Values.vpa.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.vpa.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "homarr.name" . }}
  {{- with .Values.vpa.updatePolicy }}
  updatePolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- if .Values.vpa.containerPolicies }}
  resourcePolicy:
    containerPolicies:
      {{- toYaml .Values.vpa.containerPolicies | nindent 6 }}
  {{- end }}
{{- end }}
