{{- if and (not .Values.persistence.volumeClaimTemplates.enabled) (or .Values.persistence.data.enabled .Values.persistence.config.enabled .Values.persistence.tmp.enabled) }}
{{- if .Values.persistence.data.enabled }}
{{- if not .Values.persistence.data.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "semaphore.dataPvcName" . }}
  namespace: {{ include "semaphore.namespace" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  {{- with .Values.persistence.data.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
{{- end }}
{{- end }}
{{- if .Values.persistence.config.enabled }}
{{- if not .Values.persistence.config.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "semaphore.configPvcName" . }}
  namespace: {{ include "semaphore.namespace" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
  {{- with .Values.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.config.accessMode }}
  {{- with .Values.persistence.config.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.config.size }}
{{- end }}
{{- end }}
{{- if .Values.persistence.tmp.enabled }}
{{- if not .Values.persistence.tmp.existingClaim }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "semaphore.tmpPvcName" . }}
  namespace: {{ include "semaphore.namespace" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
  {{- with .Values.persistence.tmp.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.tmp.accessMode }}
  {{- with .Values.persistence.tmp.storageClassName }}
  storageClassName: {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.tmp.size }}
{{- end }}
{{- end }}
{{- end }}
