{{- if .Values.runnerDeployment.enabled }}
{{- if not .Values.runnerDeployment.server.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semaphore.fullname" . }}-runner
  namespace: {{ include "semaphore.namespace" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
type: Opaque
data:
  runner-token: {{ .Values.runnerDeployment.server.registrationToken | required "runnerDeployment.server.registrationToken is required when runner deployment is enabled" | b64enc | quote }}
{{- end }}
{{- end }}
