{{- if .Values.runnerDeployment.enabled }}
{{- if .Values.runnerDeployment.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "semaphore.runner.serviceAccountName" . }}
  namespace: {{ include "semaphore.namespace" . }}
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
  {{- with .Values.runnerDeployment.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.runnerDeployment.serviceAccount.automount }}
automountServiceAccountToken: true
{{- else }}
automountServiceAccountToken: false
{{- end }}
{{- end }}
{{- end }}
