{{- if and .Values.cookies.enabled (not .Values.cookies.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metube.cookiesSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  cookies.txt: {{ .Values.cookies.content | b64enc | quote }}
{{- end }}
---
{{- if and .Values.tls.enabled (not .Values.tls.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "metube.tlsSecretName" . }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.certFile | b64enc | quote }}
  tls.key: {{ .Values.tls.keyFile | b64enc | quote }}
{{- end }}
