apiVersion: v2
name: homarr
description: A Helm chart for Homarr - A simple, yet powerful dashboard for your server

type: application

# Helm chart Version
version: 1.0.0

# Application version
appVersion: "latest"

keywords:
  - homarr
  - dashboard
  - home-server
  - kubernetes
  - monitoring

home: https://homarr.dev
sources:
  - https://github.com/homarr-labs/homarr

maintainers:
- name: codefuturist
  email: 58808821+codefuturist@users.noreply.github.com

icon: https://homarr.dev/img/logo.png
