{{- if not .Values.bitwarden.auth.existingSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden-eso-provider.fullname" . }}-credentials
  labels:
    {{- include "bitwarden-eso-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.bitwarden.auth.useApiKey }}
  {{ .Values.bitwarden.auth.existingSecret.clientIdKey }}: {{ .Values.bitwarden.auth.credentials.clientId | quote }}
  {{ .Values.bitwarden.auth.existingSecret.clientSecretKey }}: {{ .Values.bitwarden.auth.credentials.clientSecret | quote }}
  {{- else if .Values.bitwarden.auth.usePassword }}
  {{ .Values.bitwarden.auth.existingSecret.emailKey }}: {{ .Values.bitwarden.auth.credentials.email | quote }}
  {{ .Values.bitwarden.auth.existingSecret.passwordKey }}: {{ .Values.bitwarden.auth.credentials.password | quote }}
  {{- end }}
{{- end }}
{{- if not .Values.api.existingSecret.name }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden-eso-provider.fullname" . }}-api-token
  labels:
    {{- include "bitwarden-eso-provider.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.api.existingSecret.key }}: {{ .Values.api.token | default (randAlphaNum 32) | quote }}
{{- end }}
