{{- if and .Values.runnerDeployment.enabled (gt (len .Values.runnerDeployment.privateKeys) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "semaphore.fullname" . }}-runner-ssh
  labels:
    {{- include "semaphore.labels" . | nindent 4 }}
    app.kubernetes.io/component: runner
type: Opaque
data:
  {{- range .Values.runnerDeployment.privateKeys }}
  {{ .name }}: {{ .key | b64enc | quote }}
  {{- end }}
{{- end }}
