{{- if include "restic-backup.createSecret" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "restic-backup.secretName" . }}
  namespace: {{ include "restic-backup.namespace" . }}
  labels:
    {{- include "restic-backup.labels" . | nindent 4 }}
type: Opaque
stringData:
  RESTIC_REPOSITORY: {{ .Values.restic.repository | quote }}
  RESTIC_PASSWORD: {{ .Values.restic.password | quote }}
  {{- range $key, $value := .Values.restic.backendEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
