{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.config.secretKey | default (randAlphaNum 64) | b64enc | quote }}
  {{- if .Values.config.adminPassword }}
  admin-password: {{ .Values.config.adminPassword | b64enc | quote }}
  {{- end }}
  {{- if and (eq (include "paperless-ngx.database.engine" .) "postgresql") (not .Values.postgresql.enabled) (not .Values.database.postgresql.existingSecret) .Values.database.postgresql.password }}
  database-password: {{ .Values.database.postgresql.password | b64enc | quote }}
  {{- else if and (eq (include "paperless-ngx.database.engine" .) "mariadb") (not .Values.database.mariadb.existingSecret) .Values.database.mariadb.password }}
  database-password: {{ .Values.database.mariadb.password | b64enc | quote }}
  {{- end }}
  {{- if and (not .Values.redis.existingSecret) (not (and .Values.redis.enabled .Values.redis.auth.enabled)) .Values.redis.password }}
  redis-password: {{ .Values.redis.password | b64enc | quote }}
  {{- end }}
  {{- if and .Values.email.enabled (not .Values.email.existingSecret) .Values.email.password }}
  email-password: {{ .Values.email.password | b64enc | quote }}
  {{- end }}
{{- end }}
