{{- if not .Values.postgresql.existingSecret }}
{{- $secretName := include "postgresql.fullname" . -}}
{{- $secretNamespace := include "postgresql.namespace" . -}}
{{- $existingSecret := lookup "v1" "Secret" $secretNamespace $secretName -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $secretNamespace }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
  {{- with .Values.additionalAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- if .Values.postgresql.password }}
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  {{- else if and $existingSecret (index $existingSecret.data "postgresql-password") }}
  postgresql-password: {{ index $existingSecret.data "postgresql-password" }}
  {{- else }}
  postgresql-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.postgresPassword }}
  postgresql-postgres-password: {{ .Values.postgresql.postgresPassword | b64enc | quote }}
  {{- else if and $existingSecret (index $existingSecret.data "postgresql-postgres-password") }}
  postgresql-postgres-password: {{ index $existingSecret.data "postgresql-postgres-password" }}
  {{- else }}
  postgresql-postgres-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- if .Values.replication.enabled }}
  {{- if .Values.replication.password }}
  replication-password: {{ .Values.replication.password | b64enc | quote }}
  {{- else if and $existingSecret (index $existingSecret.data "replication-password") }}
  replication-password: {{ index $existingSecret.data "replication-password" }}
  {{- else }}
  replication-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
