{{- if .Values.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "postgresql.fullname" . }}
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: {{ ternary "StatefulSet" "Deployment" .Values.statefulset.enabled }}
    name: {{ include "postgresql.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.vpa.updateMode }}
  {{- with .Values.vpa.resourcePolicy }}
  resourcePolicy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
