{{- if and .Values.backup.enabled .Values.backup.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "postgresql.fullname" . }}-backup
  namespace: {{ include "postgresql.namespace" . }}
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    {{- range .Values.backup.persistence.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size | quote }}
  {{- if .Values.backup.persistence.storageClass }}
  {{- if (eq "-" .Values.backup.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.backup.persistence.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
