{{- if .Values.homeassistant.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "home-assistant.fullname" . }}-secrets
  namespace: {{ include "home-assistant.namespace" . }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
type: Opaque
stringData:
  secrets.yaml: |
    {{- toYaml .Values.homeassistant.secrets | nindent 4 }}
{{- end }}
