replicaCount: 1

image:
  tag: "17"

persistence:
  enabled: true
  size: 1Gi

config: {}

initScripts: {}

users:
  - name: testuser
    password: testpass123
    databases:
      - name: testdb
        extensions:
          - pg_stat_statements
