{{- if not .Values.pgadmin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.fullname" . }}
  namespace: {{ include "pgadmin.namespace" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.pgadmin.existingSecretEmailKey }}: {{ .Values.pgadmin.email | b64enc | quote }}
  {{ .Values.pgadmin.existingSecretPasswordKey }}: {{ .Values.pgadmin.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.pgadmin.smtp.enabled (not .Values.pgadmin.smtp.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.smtpSecretName" . }}
  namespace: {{ include "pgadmin.namespace" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.pgadmin.smtp.existingSecretUsernameKey }}: {{ .Values.pgadmin.smtp.username | b64enc | quote }}
  {{ .Values.pgadmin.smtp.existingSecretPasswordKey }}: {{ .Values.pgadmin.smtp.password | b64enc | quote }}
{{- end }}
---
{{- if and .Values.pgadmin.pgpassFile (not .Values.pgadmin.existingPgpassSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgadmin.pgpassSecretName" . }}
  namespace: {{ include "pgadmin.namespace" . }}
  labels:
    {{- include "pgadmin.labels" . | nindent 4 }}
type: Opaque
data:
  pgpass: {{ .Values.pgadmin.pgpassFile | b64enc | quote }}
{{- end }}
