{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "pbs.fullname" . }}
  namespace: {{ include "pbs.namespace" . }}
  labels:
    {{- include "pbs.labels" . | nindent 4 }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "pbs.fullname" . }}
  namespace: {{ include "pbs.namespace" . }}
  labels:
    {{- include "pbs.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "pbs.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pbs.serviceAccountName" . }}
    namespace: {{ include "pbs.namespace" . }}
{{- end }}
