# Example Secret for user passwords
# This can be used with postgresql.externalResources.usersSecret
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-user-passwords
  namespace: default
type: Opaque
stringData:
  # Password for myapp_user
  myapp-password: "myapp_strong_password_123"
  # Password for readonly_user
  readonly-password: "readonly_strong_password_456"
  # Password for analytics_user
  analytics-password: "analytics_strong_password_789"
