{{- if .Values.compassWeb.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "compass-web.fullname" . }}
  namespace: {{ include "compass-web.namespace" . }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.compassWeb.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
