{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "compass-web.fullname" . }}
  namespace: {{ include "compass-web.namespace" . }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "compass-web.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
