{{- if .Values.monitoring.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "compass-web.fullname" . }}
  namespace: {{ default (include "compass-web.namespace" .) .Values.monitoring.prometheusRule.namespace }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
    {{- with .Values.monitoring.prometheusRule.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: compass-web
      interval: 30s
      rules:
        {{- toYaml .Values.monitoring.prometheusRule.rules | nindent 8 }}
{{- end }}
