{{- if not .Values.compassWeb.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compass-web.fullname" . }}
  namespace: {{ include "compass-web.namespace" . }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.compassWeb.existingSecretKey }}: {{ .Values.compassWeb.mongoUri | quote }}
{{- end }}
---
{{- if and .Values.compassWeb.basicAuth.enabled (not .Values.compassWeb.basicAuth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compass-web.basicAuthSecretName" . }}
  namespace: {{ include "compass-web.namespace" . }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.compassWeb.basicAuth.existingSecretUsernameKey }}: {{ .Values.compassWeb.basicAuth.username | quote }}
  {{ .Values.compassWeb.basicAuth.existingSecretPasswordKey }}: {{ .Values.compassWeb.basicAuth.password | quote }}
{{- end }}
---
{{- if and .Values.compassWeb.genAI.enabled (not .Values.compassWeb.genAI.existingSecret) .Values.compassWeb.genAI.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "compass-web.genAISecretName" . }}
  namespace: {{ include "compass-web.namespace" . }}
  labels:
    {{- include "compass-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.compassWeb.genAI.existingSecretKey }}: {{ .Values.compassWeb.genAI.apiKey | quote }}
{{- end }}
