{{- if not .Values.mailrise.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mailrise.fullname" . }}
  namespace: {{ include "mailrise.namespace" . }}
  labels:
    {{- include "mailrise.labels" . | nindent 4 }}
data:
  mailrise.conf: |
    {{- .Values.mailrise.config | toYaml | nindent 4 }}
{{- end }}
