{{- if not .Values.pbs.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pbs.fullname" . }}
  namespace: {{ include "pbs.namespace" . }}
  labels:
    {{- include "pbs.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.pbs.existingSecretUsernameKey }}: {{ .Values.pbs.username | b64enc | quote }}
  {{ .Values.pbs.existingSecretPasswordKey }}: {{ .Values.pbs.password | b64enc | quote }}
{{- end }}
