{{- if and .Values.paperlessAi.enabled .Values.paperlessAi.persistence.enabled (not .Values.paperlessAi.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.paperlessAi.pvc" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: paperless-ai
  {{- with .Values.paperlessAi.persistence.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.paperlessAi.persistence.accessModes }}
    - {{ . }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.paperlessAi.persistence.size | quote }}
  {{- if .Values.paperlessAi.persistence.storageClass }}
  storageClassName: {{ .Values.paperlessAi.persistence.storageClass | quote }}
  {{- end }}
{{- end }}
