{{- if and .Values.persistence.data.enabled (not .Values.persistence.data.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.pvc.data" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: data
  {{- with .Values.persistence.data.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.data.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size | quote }}
  {{- if .Values.persistence.data.storageClass }}
  {{- if (eq "-" .Values.persistence.data.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.data.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.media.enabled (not .Values.persistence.media.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.pvc.media" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: media
  {{- with .Values.persistence.media.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.media.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.media.size | quote }}
  {{- if .Values.persistence.media.storageClass }}
  {{- if (eq "-" .Values.persistence.media.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.media.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.consume.enabled (not .Values.persistence.consume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.pvc.consume" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: consume
  {{- with .Values.persistence.consume.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.consume.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.consume.size | quote }}
  {{- if .Values.persistence.consume.storageClass }}
  {{- if (eq "-" .Values.persistence.consume.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.consume.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- if and .Values.persistence.export.enabled (not .Values.persistence.export.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "paperless-ngx.pvc.export" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
    app.kubernetes.io/component: export
  {{- with .Values.persistence.export.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    {{- range .Values.persistence.export.accessModes }}
    - {{ . | quote }}
    {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.export.size | quote }}
  {{- if .Values.persistence.export.storageClass }}
  {{- if (eq "-" .Values.persistence.export.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.export.storageClass | quote }}
  {{- end }}
  {{- end }}
{{- end }}
