{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default (include "home-assistant.namespace" .) }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "home-assistant.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- if and .Values.serviceMonitor.bearerToken.secretName .Values.serviceMonitor.bearerToken.secretKey }}
      bearerTokenSecret:
        name: {{ .Values.serviceMonitor.bearerToken.secretName }}
        key: {{ .Values.serviceMonitor.bearerToken.secretKey }}
      {{- end }}
{{- end }}
