apiVersion: v2
name: test-final
description: Test chart with auto-version
type: application
version: 1.0.0
appVersion: "1.27.3"

keywords:
  - test-final
  - kubernetes

home: https://example.com
sources:
  - https://github.com/example/app
  - https://github.com/codefuturist/helm-charts

maintainers:
  - name: codefuturist
    email: 58808821+codefuturist@users.noreply.github.com

icon: https://example.com/icon.png

dependencies:
  - name: common
    repository: file://../../libs/common
    version: 2.x.x
    tags:
      - bitnami-common

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of test-final Helm chart v0.1.0

