{{- if .Values.sealedSecrets.enabled }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "pihole.fullname" . }}
  namespace: {{ include "pihole.namespace" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.sealedSecrets.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- if eq $.Values.sealedSecrets.scope "namespace-wide" }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{- else if eq $.Values.sealedSecrets.scope "cluster-wide" }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{- end }}
  {{- else }}
  annotations:
    {{- if eq .Values.sealedSecrets.scope "namespace-wide" }}
    sealedsecrets.bitnami.com/namespace-wide: "true"
    {{- else if eq .Values.sealedSecrets.scope "cluster-wide" }}
    sealedsecrets.bitnami.com/cluster-wide: "true"
    {{- end }}
  {{- end }}
spec:
  encryptedData:
    {{- toYaml .Values.sealedSecrets.encryptedData | nindent 4 }}
  template:
    metadata:
      name: {{ include "pihole.fullname" . }}
      namespace: {{ include "pihole.namespace" . }}
      labels:
        {{- include "pihole.labels" . | nindent 8 }}
    type: Opaque
{{- end }}
