{{- if .Values.secretProviderClass.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretProviderClass.name | default (include "pihole.fullname" .) }}
  namespace: {{ include "pihole.namespace" . }}
  labels:
    {{- include "pihole.labels" . | nindent 4 }}
  {{- with .Values.secretProviderClass.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  provider: {{ required "secretProviderClass.provider is required when secretProviderClass.enabled is true" .Values.secretProviderClass.provider }}
  {{- with .Values.secretProviderClass.parameters }}
  parameters:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.secretProviderClass.secretObjects }}
  secretObjects:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
