{{- if and .Values.mailrise.auth.enabled (not .Values.mailrise.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mailrise.fullname" . }}-auth
  namespace: {{ include "mailrise.namespace" . }}
  labels:
    {{- include "mailrise.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $user, $password := .Values.mailrise.auth.users }}
  {{ $user }}: {{ $password | quote }}
  {{- end }}
{{- end }}
