apiVersion: v2
name: bitwarden-eso-provider
description: A Bitwarden webhook provider for External Secrets Operator that works with personal/organizational vaults using the Bitwarden CLI
type: application
version: 1.0.2
appVersion: "1.0.0"

keywords:
  - bitwarden
  - secrets
  - external-secrets
  - eso
  - webhook
  - security

home: https://github.com/codefuturist/helm-charts
sources:
  - https://github.com/codefuturist/helm-charts
  - https://github.com/codefuturist/helm-charts/tree/main/apps/bitwarden-eso-provider-app

maintainers:
  - name: codefuturist
    email: 58808821+codefuturist@users.noreply.github.com

annotations:
  category: Security
