apiVersion: v2
name: it-tools
description: A Helm chart for IT Tools - Useful tools for developers
type: application
version: 1.0.0
appVersion: "latest"

keywords:
  - it-tools
  - kubernetes

home: https://github.com/sharevb/it-tools
sources:
  - https://github.com/sharevb/it-tools
  - https://github.com/codefuturist/helm-charts

maintainers:
  - name: codefuturist
    email: 58808821+codefuturist@users.noreply.github.com

icon: https://raw.githubusercontent.com/sharevb/it-tools/main/public/favicon.ico

dependencies:
  - name: common
    repository: file://../../libs/common
    version: 2.x.x
    tags:
      - bitnami-common

annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial release of it-tools Helm chart v0.1.0

